### ISSUE TITLE
Unauthorized AuthId Permission Denied

### ISSUE THREAD

**Issue by ajax-2** [gy-games/elves#1]
在使用rt任务的时候，出现了Unauthorized AuthId Permission Denied 这个问题，但是authid和authkey用于appinfo信息获取是对的，timestamp两边的获取方式也是一样的。

elves-center 是通过docker安装的
agent 通过git clone的最新版

**Comment by eastFu** [comment]
这个是AuthId 的权限问题，AuthId 权限包括：是否有权限操作此APP和是否有权限操作这台机器IP。
所以有两个地方你去supervisor上确认。
第一个：使用的这个AuthId 是否可以调用这个APP
第二个：这个APP是否授权了此机器IP。

**Comment by ajax-2** [comment]
有的，我只有一个app和一台机器来测试，center 和 agent都在一台机器上。
agent里面authips 也加上了这台机器，supervisor也正常操作了
![image](https://user-images.githubusercontent.com/29370146/70116920-0b18b080-169f-11ea-90c2-40ab71e96efa.png)
![image](https://user-images.githubusercontent.com/29370146/70116932-17047280-169f-11ea-8c2d-58faef48dca3.png)
![image](https://user-images.githubusercontent.com/29370146/70116959-271c5200-169f-11ea-84ac-444f88ea98e0.png)
app名中文英文都试过了

**Comment by ajax-2** [comment]
我把agent的ip从127换成了192的，然后通过换了之后authid通过了
